apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: systtek/multi-client
        resources:
          limits:
            memory: "128Mi"
            cpu: "80m"
          requests:
            memory: "64Mi"
            cpu: "50m"